package mapsidproof;

import static org.assertj.core.api.Assertions.assertThat;

import dev.alkolhar.servdesk.classification.Category;
import dev.alkolhar.servdesk.classification.Priority;
import dev.alkolhar.servdesk.common.MapsIdBaseEntity;
import dev.alkolhar.servdesk.directory.Person;
import dev.alkolhar.servdesk.directory.PersonRole;
import dev.alkolhar.servdesk.directory.Team;
import dev.alkolhar.servdesk.ticket.Ticket;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import org.hibernate.SessionFactory;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.mariadb.MariaDBContainer;

/**
 * Proves the id-sharing mechanic {@link MapsIdBaseEntity} exists for: a subtype
 * entity persisted with {@code @OneToOne @MapsId} against {@link Ticket},
 * sharing its primary key rather than generating its own (see ADR-0001).
 * Deliberately bypasses the application's Spring context and
 * {@code V1__init_schema.sql} — {@link MapsIdFixture} is a test-only stand-in
 * for a real subtype (Incident, Problem, ...), so its schema is generated by
 * Hibernate directly against a throwaway container rather than added to the
 * production migration. Lives outside {@code dev.alkolhar.servdesk} so its
 * {@code @Entity} fixture is never swept up by the application's own classpath
 * entity scan (which would otherwise fail {@code ddl-auto=validate} in every
 * other Spring-context test, since no such table is migrated).
 */
@Testcontainers
class MapsIdBaseEntityTest {

	@Container
	private static final MariaDBContainer mariaDb = new MariaDBContainer("mariadb:latest");

	private static SessionFactory sessionFactory;

	@Entity
	@Table(name = "maps_id_fixture")
	static class MapsIdFixture extends MapsIdBaseEntity {

		@OneToOne
		@MapsId
		@JoinColumn(name = "id")
		private Ticket ticket;

		@Column(nullable = false)
		private String note;

		Ticket getTicket() {
			return ticket;
		}

		void setTicket(Ticket ticket) {
			this.ticket = ticket;
		}

		String getNote() {
			return note;
		}

		void setNote(String note) {
			this.note = note;
		}
	}

	@BeforeAll
	static void buildSessionFactory() {
		StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
				.applySetting("hibernate.connection.url", mariaDb.getJdbcUrl())
				.applySetting("hibernate.connection.username", mariaDb.getUsername())
				.applySetting("hibernate.connection.password", mariaDb.getPassword())
				.applySetting("hibernate.connection.driver_class", "org.mariadb.jdbc.Driver")
				.applySetting("hibernate.hbm2ddl.auto", "create-drop").build();
		sessionFactory = new MetadataSources(registry).addAnnotatedClass(Team.class).addAnnotatedClass(Category.class)
				.addAnnotatedClass(Priority.class).addAnnotatedClass(Person.class).addAnnotatedClass(Ticket.class)
				.addAnnotatedClass(MapsIdFixture.class).buildMetadata().buildSessionFactory();
	}

	@AfterAll
	static void closeSessionFactory() {
		if (sessionFactory != null) {
			sessionFactory.close();
		}
	}

	@Test
	void subtypeEntitySharesTicketsPrimaryKeyViaMapsId() {
		Long ticketId = sessionFactory.fromTransaction(session -> {
			Person requester = new Person();
			requester.setRole(PersonRole.CUSTOMER);
			requester.setName("Carla Customer");
			requester.setEmail("carla@example.com");
			session.persist(requester);

			Ticket ticket = new Ticket();
			ticket.setSubject("Printer on fire");
			ticket.setRequester(requester);
			session.persist(ticket);

			MapsIdFixture fixture = new MapsIdFixture();
			fixture.setTicket(ticket);
			fixture.setNote("root cause: toner overheating");
			session.persist(fixture);

			return ticket.getId();
		});

		sessionFactory.inTransaction(session -> {
			MapsIdFixture reloaded = session.find(MapsIdFixture.class, ticketId);

			assertThat(reloaded).isNotNull();
			assertThat(reloaded.getId()).isEqualTo(ticketId);
			assertThat(reloaded.getTicket().getId()).isEqualTo(ticketId);
			assertThat(reloaded.getNote()).isEqualTo("root cause: toner overheating");
		});
	}
}
